/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./assets/js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e1",
        "surface-variant": "#353434",
        "surface-tint": "#c9c6c5",
        "tertiary-container": "#080a0a",
        "on-secondary": "#2f3131",
        "secondary-container": "#484949",
        "on-tertiary": "#2f3131",
        "surface-container-low": "#1c1b1b",
        "on-error": "#690005",
        "on-primary-container": "#7b7979",
        "tertiary": "#c6c6c6",
        "primary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "surface-dim": "#141313",
        "surface-container-high": "#2b2a2a",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed-variant": "#464747",
        "on-secondary-container": "#b8b8b8",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-primary": "#313030",
        "outline-variant": "#444748",
        "on-surface-variant": "#c4c7c7",
        "error": "#ffb4ab",
        "inverse-on-surface": "#313030",
        "on-tertiary-container": "#78797a",
        "on-secondary-fixed": "#1a1c1c",
        "surface-container-highest": "#353434",
        "on-primary-fixed-variant": "#474646",
        "on-primary-fixed": "#1c1b1b",
        "secondary-fixed": "#e3e2e2",
        "surface-container": "#201f1f",
        "surface-bright": "#3a3939",
        "inverse-primary": "#5f5e5e",
        "on-tertiary-fixed-variant": "#454747",
        "surface": "#141313",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-container": "#0a0a0a",
        "on-surface": "#e5e2e1",
        "background": "#141313",
        "primary": "#c9c6c5",
        "outline": "#8e9192",
        "secondary-fixed-dim": "#c7c6c6",
        "secondary": "#c7c6c6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "container-max": "1440px",
        "margin-edge": "40px",
        "element-gap": "16px",
        "section-padding": "120px",
      },
      fontFamily: {
        "lang-toggle": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        h3: ["Montserrat", "sans-serif"],
        h1: ["Montserrat", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        h2: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "lang-toggle": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        h3: ["32px", { lineHeight: "1.2", letterSpacing: "0em", fontWeight: "700" }],
        h1: ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        h2: ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
